language: c++
compiler:
  - clang
  - gcc
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libyajl-dev libxml2-dev libxqilla-dev
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qqy 
libstdc++-4.8-dev; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qqy g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
install:
  - curl -O http://www.libsdl.org/release/SDL2-2.0.0.tar.gz
  - tar -xzvf SDL2-2.0.0.tar.gz
  - (cd SDL2-2.0.0 && ./configure && make && sudo make install)
script:
  - mkdir build && cd build
  - cmake ..
  - make
